import { withHexAlpha } from "../color";
import type { ThemeRoles } from "../types";

/** Color keys for @pierre/diffs and themeToTreeStyles. */
export function rolesToVscodeColors(roles: ThemeRoles): Record<string, string> {
  const { bg, fg, border, accent, states, list } = roles;

  return {
    "editor.background": bg.editor,
    "editor.foreground": fg.base,
    foreground: fg.base,
    "editor.lineHighlightBackground": withHexAlpha(bg.elevated, 0x8c),
    "editor.selectionBackground": accent.subtle,
    "editorLineNumber.foreground": fg.muted,
    "editorLineNumber.activeForeground": fg.accentBright,
    "editorIndentGuide.background": bg.editor,
    "editorIndentGuide.activeBackground": bg.elevated,
    "editorCursor.foreground": accent.primary,
    "diffEditor.insertedTextBackground": withHexAlpha(states.success, 0x1f),
    "diffEditor.deletedTextBackground": withHexAlpha(states.danger, 0x1f),
    "diffEditor.insertedLineBackground": withHexAlpha(states.success, 0x14),
    "diffEditor.removedLineBackground": withHexAlpha(states.danger, 0x14),
    "sideBar.background": bg.window,
    "sideBar.foreground": fg.muted,
    "sideBar.border": "transparent",
    "sideBarTitle.foreground": fg.accentBright,
    "sideBarSectionHeader.background": bg.window,
    "sideBarSectionHeader.foreground": fg.muted,
    "sideBarSectionHeader.border": "transparent",
    "list.activeSelectionBackground": list.activeSelectionBg,
    "list.activeSelectionForeground": list.activeSelectionFg,
    "list.inactiveSelectionBackground": list.inactiveSelectionBg,
    "list.hoverBackground": list.hoverBg,
    "list.focusOutline": border.focus,
    focusBorder: border.focus,
    "selection.background": accent.subtle,
    "panel.background": bg.editor,
    "panel.border": border.default,
    "tab.activeBackground": bg.editor,
    "tab.inactiveBackground": bg.editor,
    "tab.border": border.default,
    "input.background": bg.inset,
    "input.border": border.default,
    "input.foreground": fg.base,
    "input.placeholderForeground": fg.muted,
    "dropdown.background": bg.elevated,
    "dropdown.border": border.default,
    "dropdown.foreground": fg.base,
    "scrollbarSlider.background": list.scrollbar,
    "gitDecoration.addedResourceForeground": states.success,
    "gitDecoration.modifiedResourceForeground": states.modified,
    "gitDecoration.deletedResourceForeground": states.danger,
    "gitDecoration.conflictingResourceForeground": states.modified,
    "gitDecoration.untrackedResourceForeground": states.success,
    "gitDecoration.ignoredResourceForeground": fg.muted,
    "textLink.foreground": accent.primary,
    "textLink.activeForeground": accent.primary,
    "terminal.ansiGreen": states.success,
    "terminal.ansiRed": states.danger,
    "terminal.ansiBlue": states.modified,
  };
}
