[package]
name = "diffview"
version = "0.1.0"
description = "Local branch diff viewer"
authors = ["sergichafer"]
license = "MIT"
edition = "2021"

[lib]
name = "diffview_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
git2 = "0.20"
typeshare = "1"
tauri-plugin-cli = "2"
